ruby '2.4.0'

source 'https://rubygems.org/'

gem 'sinatra',			    '~> 1.4', '>= 1.4.8'
gem 'sinatra-contrib',  '~> 1.4', '>= 1.4.7'
gem 'erubis',			      '~> 2.7'
gem 'minitest',			    '~> 5.8', '>= 5.8.4'
gem 'redcarpet',        '~> 3.4'
